[build]
  command = "npm run build"

[functions]
  directory = "netlify/functions"  

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_SITE_ID = "42d66233-8300-4235-ac19-223e4605cabb"